<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TMOOD" ignored="0" name="Test" tests="1" failures="1" timestamp="02 Jan 2019 20:10:45 GMT" time="4.021" errors="0">
  <testcase name="books" time="3.942" classname="Tests.GetBooks">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON documentat io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)at io.restassured.path.json.JsonPath.get(JsonPath.java:201)at io.restassured.path.json.JsonPath.getList(JsonPath.java:374)at Tests.GetBooks.books(GetBooks.java:24)Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)at groovy.json.JsonLexer$nextToken.call(Unknown Source)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)... 30 more... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- books -->
</testsuite> <!-- Test -->
